# conda env create -f environment.yml

name: PianoKPM
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python==3.10.16
  - numpy==2.0.1
  - pip==25.0
  - pip:
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.11.16
    - aiosignal==1.3.2
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - async-timeout==5.0.1
    - attrs==25.3.0
    - av==14.3.0
    - Brotli
    - certifi
    - charset-normalizer
    - click==8.1.8
    - contourpy==1.3.1
    - cycler==0.12.1
    - docker-pycreds==0.4.0
    - einops==0.8.1
    - filelock
    - fonttools==4.56.0
    - frozenlist==1.5.0
    - fsspec==2025.3.2
    - geomloss==0.2.6
    - gitdb==4.0.12
    - GitPython==3.1.44
    - gmpy2
    - h5py==3.13.0
    - huggingface-hub==0.30.1
    - hydra-core==1.3.2
    - idna
    - Jinja2
    - joblib==1.4.2
    - keopscore==2.3
    - kiwisolver==1.4.8
    - lightning-utilities==0.14.3
    - MarkupSafe
    - matplotlib==3.10.1
    - mkl-service==2.4.0
    - mkl_fft
    - mkl_random
    - mpmath
    - multidict==6.4.3
    - narwhals==1.36.0
    - networkx
    - numpy
    - omegaconf==2.3.0
    - opencv-python==4.11.0.86
    - packaging==24.2
    - pandas==2.2.3
    - pillow
    - platformdirs==4.3.7
    - plotly==6.0.1
    - propcache==0.3.1
    - protobuf==5.29.4
    - psutil==7.0.0
    - pybind11==2.13.6
    - pydantic==2.11.1
    - pydantic_core==2.33.0
    - pykeops==2.3
    - pyparsing==3.2.3
    - PySocks
    - python-dateutil==2.9.0.post0
    - pytorch-lightning==2.5.1
    - pytz==2025.2
    - PyYAML
    - requests
    - safetensors==0.5.3
    - scikit-learn==1.6.1
    - scipy==1.15.2
    - sentry-sdk==2.25.0
    - setproctitle==1.3.5
    - six==1.17.0
    - smmap==5.0.2
    - sympy==1.13.1
    - threadpoolctl==3.6.0
    - torch==2.5.1
    - torchaudio==2.5.1
    - torchmetrics==1.7.1
    - torchvision==0.20.1
    - tqdm==4.67.1
    - triton==3.1.0
    - typing-inspection==0.4.0
    - typing_extensions
    - tzdata==2025.2
    - urllib3
    - yarl==1.19.0