_target_: module.networks.PianoKPMNetwork_multimodal

pose_conv_blocks:
  - _target_: module.networks.Conv1dBlock
    in_channels: 84 # input feature channels
    out_channels: 256
    kernel_size: 11
    stride: 1
    padding: 5
  - _target_: module.networks.Conv1dBlock
    in_channels: 256
    out_channels: 256
    kernel_size: 5
    stride: 1
    padding: 2

key_conv_blocks:
  - _target_: module.networks.Conv1dBlock
    in_channels: 88 # input feature channels
    out_channels: 256
    kernel_size: 11
    stride: 1
    padding: 5
  - _target_: module.networks.Conv1dBlock
    in_channels: 256
    out_channels: 256
    kernel_size: 5
    stride: 1
    padding: 2

tds_stages:
  - _target_: module.networks.TcwEncoder
    in_channels: 256
    in_conv_kernel_width: 17
    in_conv_stride: 1
    in_conv_padding: 8
    num_blocks: 2
    # Total channel depth is channels * feature_width
    channels: 16
    feature_width: 16
    kernel_width: 9
  - _target_: module.networks.TcwEncoder
    in_channels: 256
    in_conv_kernel_width: 9
    in_conv_stride: 1
    in_conv_padding: 4
    num_blocks: 2
    # Total channel depth is channels * feature_width
    channels: 16
    feature_width: 16
    kernel_width: 5
    out_channels: 64
